org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4g

group=dev.franwdev
version=1.0.0
archive_name=soulslikeregen-1.21.1-neoforge

mod_name=SoulslikeRegen
mod_author=KMC
mod_id=soulslikeregen
mod_license=MIT

minecraft_version=1.21.1
neoforge_version=21.1.8

# Dependencies CurseForge IDs
waystones_cf_id=245755:8777999
balm_cf_id=531761:8645517
ftbteams_cf_id=404468:8724782

